version: 2
workflows:
  version: 2
  worldping-gw:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    working_directory: /go/src/github.com/grafana/worldping-gw
    docker:
      - image: circleci/golang:1.11.3
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make test
      - run:
          name: build binary
          command: make build
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: build
          # Must be relative path from root
          paths:
            - worldping-gw
  deploy:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: build
      - run:
          name: build docker image
          command: make docker
      - run:
          name: login to dockerhub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: deploy docker image
          command: make deploy
